### ISSUE TITLE
Write an assembly guide

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#3]
From the draft (word document) and images available for download in this issue, write a comprehensive assembly guide (in markdown) for 3.0.0 release.

Indicative due date : April 30th, 2017

Criteria to close the issue :

- Update the prototyping gitbook (https://echopen.gitbooks.io/echopen_prototyping/) with the assembly guide.
- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown file : stable/guide_hardware.md
- Make a pull request refering to this issue

Preliminary version of the files :

[guide_montage.zip](https://github.com/echopen/echopen_prototyping/files/886415/guide_montage.zip)

**Comment by kelu124** [comment]
WIll be waiting for your file @Aurelie-Mutschler  =)

**Comment by Aurelie-Mutschler** [comment]
@kelu124 just pushed a preliminary version of the files ;-) will update them as soon as possible

**Comment by Aurelie-Mutschler** [comment]
@kelu124 just updated the files, now only the part about mechanics is missing !

**Comment by Aurelie-Mutschler** [comment]
note for myself : some schemes modified by Jérôme have to be changed in the .md

**Comment by Aurelie-Mutschler** [comment]
note for @kelu124 : @jerome2echopen has made a BOM per supplier, available here : https://github.com/echopen/PRJ-medtec_kit/tree/master/electronic/miscellaneous/general_BOM

please could you put that link at the beginning of the production guide ? :)

**Comment by GG23800** [comment]
For the BOM note that the Farnell BOM is only for a laboratory power supply if needed. Moreover, the hackspark BOM is for "basic" fournitures (for soldering), and for sockets (needed for the kit), in my mind it is for showing that one can buy it in it's closest electronic store.

**Comment by kelu124** [comment]
@Aurelie-Mutschler can I ask you O supreme leader to extend the deadline? Or to ask someone else to fill in the blanks?

**Comment by Aurelie-Mutschler** [comment]
@kelu124 deadline extended till the end of the month
passed that date, you'll owe me one beer per additionnal day ;-)

**Comment by kelu124** [comment]
And you'll owe me one for each day before the end of the day =)

**Comment by Aurelie-Mutschler** [comment]
Deal :D

**Comment by GG23800** [comment]
Mechanical part:

To complete the kit, one have to 3D print some pieces locate on PRJ-medtec_kit/mecanic/modules. At least we need MDL-motor_support, MDL-rod_fixation and MDL-transducer_support, with these modules we have the stricilly minimum device to make measurement in an acquarium. Use the .stl files present in the different folders for 3d printing them. Note that for the moment MDL-transducer_support will have to be adapted for your own transducer because we have not « serial » transducers to ship with our kit yet. One can do that by using freecad (open the .igs file) modify and then export in .stl file (mesh formats files).

First print MDL-motor_support, at the end it will look to something like that:

![support_raw](https://cloud.githubusercontent.com/assets/14290878/25046973/97708d2c-2134-11e7-963a-9bbfb90406ca.JPG)

![support_raw2](https://cloud.githubusercontent.com/assets/14290878/25046978/9fbb27f8-2134-11e7-8b3a-ee93e03ba91f.JPG)

Take off the plastique support, there is still plastic in the hole where we will put the motor :

![support_raw3_2](https://cloud.githubusercontent.com/assets/14290878/25046983/a92b9f20-2134-11e7-9339-b2060f1b1ce6.JPG)

Take it off too with pliers for example, and it’s finish:

![support_evide](https://cloud.githubusercontent.com/assets/14290878/25046992/b483834c-2134-11e7-8e90-a47b3b9477d1.JPG)

Now fix the motor to this support with 2 or 4 screw 3 mm diameter, 6mm long.

Now print MDL-rod-fixation, the two holes on each side of this part of the cylinder. The bigger one is for the motor axe. Fix this axis with a 3mm diameter 10 mm long screw. This screw must be 10 mm minimum cause it must stick out so it will hit the motor_support when initialising (searching it's 0). The second one is used to fix the rod, prefer using wood screw 3 mm diameter.

![montage1](https://cloud.githubusercontent.com/assets/14290878/25047010/bef0416c-2134-11e7-8c3d-3422bc4e0627.JPG)

The rod is a metal rod 4 mm diameter, prefer stainless steel, because it will be immersed in water, We use 100 mm long rod, but only limitation on the length is that the transducer must be immersed and the electrical connection of the transducer must not.

Then print the tranducer support and fix it to the rod.

![finish](https://cloud.githubusercontent.com/assets/14290878/25047014/c6fc491e-2134-11e7-980d-6d65417078cf.JPG)

**Comment by GG23800** [comment]
Update of scheme for motor_control_v3:

![bottom_view](https://cloud.githubusercontent.com/assets/14290878/25047585/efbb6af8-2137-11e7-8d1a-bad567b12147.png)

![top_view](https://cloud.githubusercontent.com/assets/14290878/25047591/f539b25a-2137-11e7-8ba0-8ab97509deef.png)

cf.: PRJ-medtec_kit/electronic/daughter_boards/DB-motor_control/DB-motor_control_v3/readme.md

**Comment by GG23800** [comment]
Arduino test code for assembly:

#define NOP asm volatile ("nop\n\t");

void pulse()
{
PORTD=B01010000;
NOP;
PORTD=B00000000;
}

void setup() {
// put your setup code here, to run once:
DDRD = B01010000;
}

void loop() {
// put your main code here, to run repeatedly:
pulse();
delayMicroseconds(500);
}

**Comment by GG23800** [comment]
Just copy past this in arduino IDE

**Comment by GG23800** [comment]
If the duration of the pulse is too long (>125 ns) delete line 6 (NOP;), this can happened with "bad" arduino copy.

**Comment by GG23800** [comment]
Note, switchs position of the TGC:
- switch LNA EN on EN
- switch VGA EN  on EN
- switch GN SLOPE on UP
- switch GN HI LO on LO

**Comment by Aurelie-Mutschler** [comment]
Will do within next days :
- complete the mechanical part + update some images
- debug : images are not displayed in the gitbook

**Comment by kelu124** [comment]
Hum I see for images. Will add absolute paths in the markdown. Commit today .

**Comment by Aurelie-Mutschler** [comment]
@kelu124 there are still images that are not displayed in the gitbook, because the paths you put in the .md are not complete. Could you have a look at it ?

**Comment by GG23800** [comment]
I just have look at assembly guide, there problems with images than are not located at the right place (image does not correspond to the text), images that are repeated and some @todo remaining.

**Comment by Aurelie-Mutschler** [comment]
@GG23800 can you confirm you're handling it ? We are releasing the documentation on July 13th ;-)

**Comment by Aurelie-Mutschler** [comment]
thanks to @halipster @kelu124 for the pictures and draft
and to @GG23800 for the amazing work ;-)
