### ISSUE TITLE
Finish merging content from the android app gitbook

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/echopen_prototyping#54]
Find where to merge remaining contents from the android app gitbook. Below are listed the files that are not yet (fully) included in the new gitbook :
- algorithms/scan-conversion.md : "Presentation of the scan conversion" has been moved to the introduction. "Current algo choice" has to be merged somewhere.
- challenges/mockup-ux/mockups-v1.md will be merged into the future iteration planning
- configuring-your-own-dataset.md
- constants.md
- install-opencv-v-20.md
- playing-with-data.md

Indicative due date : June 15th, 2017

Criteria to close the issue :

- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit some markdown files to merge the contents
- The old versions of the hacking guide are in the hacking-guide/ directory
Make a pull request refering to this issue

**Comment by benchoufi** [comment]
hi there, here are the choices @clecoued and I suggest you  

we get rid of : constants.md, install-opencv-v-20.md, challenges/mockup-ux/mockups-v1.md

- we hide in order to merge and rewrite configuring-your-own-dataset.md + playing-with-data.md -> we are going to install an emulator tool, based on @jerome2echopen [work](https://github.com/echopen/PRJ-medtec_androidapp/pull/44)

- the case of `install-opencv-v-20.md` is however interesting since it raises the question to compile some tutorials from our further developments : these are not strictly bound to the technology we . But, it has some sens to share with the community tips and tools that we manipulated even when we don't adopt them in released versions

-  concerning `scan_conversion.md` : the [part](https://www.gitbook.com/book/echopen/echopen_prototyping/edit#/edit/master/hacking-guide/algorithms/scan-conversion.md?_k=dr1tqd) that was not kept in the [technical introduction](https://www.gitbook.com/book/echopen/echopen_prototyping/edit#/edit/master/introduction/new_introduction.md?_k=ezhehz), especially the `current algo choice` section, is important : so we propose to create a `technology choices` section in the "Stable release V3.0.0/Documentation/Software folder" and put these kind of high level docs there

**Comment by Aurelie-Mutschler** [comment]
Hey guys, seems nice!

- as regards install-opencv-v-20.md, maybe it could be included in the References/ section where we store pedagogical documents in the form of single pages?
- the missing part of scan_conversion.md might also be included in this section, or we can create a "technology choice" in the stable release doc. It depends, are these informations true only for the v3 release? if not, it's maybe better not to put it in the stable release.

Just let me know if you want me to create some new subsections ;)

**Comment by benchoufi** [comment]
- ok 4 me for `install-opencv-v-20.md` @clecoued your point of view ? 

- 4 `scan_conversion.md`, the file is related to specific release since they are precisely the motivations of the choices we go through in a context of a release. So, I think that it has some sense to be put there in "technology choice". However, we must take the freedom to maintain and duplicate after a release some part/digest of this kind of informations that we feel to be of interest and to be shared with the community

**Comment by Aurelie-Mutschler** [comment]
it's done for install-opencv-v-29.md and scan_conversion.md ;-)
when will the emulator be ready ?

**Comment by benchoufi** [comment]
I think @clecoued did it - @clecoued you confirm ?

**Comment by clecoued** [comment]
@jerome did it and I reviewed it. emulator code is ready and documented in the mobile app github ;)

**Comment by Aurelie-Mutschler** [comment]
shall we document that in the gitbook? I think @benchoufi told me you wanted to include the emulator in the release ?

**Comment by Aurelie-Mutschler** [comment]
@lecoued what's the difference between this issue and #66 ?

**Comment by Aurelie-Mutschler** [comment]
🎉
